name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.2

      - name: Install Poetry
        uses: snok/install-poetry@v1.2.0
        with:
          version: 1.1.12

      - name: Install dependencies
        run: |
          python --version
          python -m site
          make install-dev

      - name: Run unit testing
        run: make test-unit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

  test-linting:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.2

      - name: Install Poetry
        uses: snok/install-poetry@v1.2.0
        with:
          version: 1.1.12

      - name: Install dependencies
        run: make install-dev

      - name: Run Flake8
        run: make test-lint

  test-docker:
    name: Testing Docker container
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker container
        run: make docker-run

      - name: Test Docker container
        run: docker container ls | grep -q "Up"
